apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestor
  template:
    metadata:
      labels:
        app: requestor
    spec:
      containers:
        - name: requestor
          image: heyal/requestor:async
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: requestor-service
spec:
  selector:
    app: requestor
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
        - name: generator
          image: heyal/generator:async
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: generator-service
spec:
  selector:
    app: generator
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
